# ── Font Settings ────────────────────────────────────────────────────────
[font]
size = 12.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style  = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style  = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style  = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style  = "Regular"

# ── Mouse & Environment ───────────────────────────────────────────────────
[mouse]
hide_when_typing = true

[env]
TERM = "xterm-256color"

# Colors Primary
[colors.primary]
background = "0x000000"
foreground = "0xffffff"

[window]
opacity = 0.95
